config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/fruits', to: 'fruits#index'

  get '/fruits/:id', to: 'fruits#show'

  post '/fruits/', to: 'fruits#create'

  get '/fruits/:id/edit', to: 'fruits#edit'

  put '/fruits/:id', to: 'fruits#update'

  delete 'fruits/:id', to: 'fruits#destroy'

  resources :bikes
  resources :bugs
  resources :songs
  resources :cars
end

app/models/bike.rb
class Bike < ActiveRecord::Base
  validates :name, presence: true
end

app/models/bug.rb
class Bug < ActiveRecord::Base

end

app/models/car.rb
class Car < ActiveRecord::Base

end

app/models/fruit.rb
class Fruit < ActiveRecord::Base

end

app/models/song.rb
class Song < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController

  def index
    @bikes = Bike.all
    @bike = Bike.new
  end

  def create
    @bike = Bike.create(bike_params)

    if @bike.save
      redirect_to bikes_path
    else
      render 'bikes/index'
    end
  end

  def show
    @bike = Bike.find(params[:id])
  end

  def edit
    @bike = Bike.find(params[:id])
  end

  def update
    @bike = Bike.find(params[:id])
    @bike.update_attributes!(bike_params)

    redirect_to bike_path(@bike)
  end

  def destroy
    @bike = Bike.find(params[:id])
    @bike.delete

    redirect_to bikes_path
  end

  private

  def bike_params
    params.require(:bike).permit(:name, :year)
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController

  def index
    @bugs = Bug.all
    @bug = Bug.new
  end

  def create
    @bug = Bug.create(bug_params)

    if @bug.save
      redirect_to bugs_path
    else
      render 'bugs/index'
    end
  end

  def show
    @bug = Bug.find(params[:id])
  end

  def edit
    @bug = Bug.find(params[:id])
  end

  def update
    @bug = Bug.find(params[:id])
    @bug.update_attributes!(bug_params)

    redirect_to bug_path(@bug)
  end

  def destroy
    @bug = Bug.find(params[:id])
    @bug.delete

    redirect_to bugs_path
  end

  private

  def bug_params
    params.require(:bug).permit(:bug_name, :color)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @car = Car.new
    @cars = Car.all
  end

  def create
    @car = Car.create(car_params)

    if @car.save
      redirect_to cars_path
    else
      render :new
    end
  end

  def show
    @car = Car.find(params[:id])
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update_attributes(car_params)

    redirect_to car_path
  end

  def destroy
    @car = Car.find(params[:id])
    @car.delete

    redirect_to cars_path
  end

  def car_params
    params.require(:car).permit(:model, :year)
  end
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController

  def index
    @fruits = Fruit.all
    @fruit = Fruit.new
  end

  def new

  end

  def show
    @fruit = Fruit.find(params[:id])
  end

  def create
    @fruit = Fruit.create(params[:id])
    @fruit.name = params[:fruit][:name]
    @fruit.description = params[:fruit][:description]

    @fruit.save
    redirect_to '/fruits'
  end

  def edit
    @fruit = Fruit.find(params[:id])

  end


  def update
    @fruit = Fruit.find(params[:id])
    @fruit.name = params[:fruit][:name]
    @fruit.description = params[:fruit][:description]

    @fruit.save

    redirect_to "/fruits/#{@fruit.id}"
  end

  def destroy
    @fruit = Fruit.find(params[:id])
    @fruit.destroy
    redirect_to '/'
  end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
    @song = Song.new
  end

  def create
    @song = Song.create(song_params)

    if @song.save
      redirect_to songs_path
    else
      render 'songs/index'
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    @song.update_attributes!(song_params)

    redirect_to song_path(@song)
  end

  def destroy
    @song = Song.find(params[:id])
    @song.delete

    redirect_to songs_path
  end

  def song_params
    params.require(:song).permit(:title, :artist)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/edit.html.erb
<h2>Update Bike</h2>

<%= form_for @bike do |f| %>

  <% if @bike.errors.present? %>
    <div class="errors">
      <h1>There was an error</h1>
      <ul class="error-list">
        <% @bike.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :year, "Year" %>
    <%= f.text_field :year %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

app/views/bikes/index.html.erb
<h2>Add A Bike</h2>

<%= form_for @bike do |f| %>

  <% if @bike.errors.present? %>
    <div class="errors">
      <h1>There was an error</h1>
      <ul class="error-list">
        <% @bike.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name, "Name", class: "form-label" %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :year, "Year", class: "form-label" %>
    <%= f.text_field :year %>
  </p>

  <p>
    <%= f.submit "Add Bike", class: "form-button" %>
  </p>
<% end %>

<table width="500" border="orange">
  <thead>
  <caption><h2>Bikes</h2></caption>
  <th>Name</th>
  <th>Year</th>
  </thead>
  <tbody>
  <% @bikes.each do |bike| %>
    <tr>
      <td><%= link_to bike.name, bike_path(bike) %></td>
      <td><%= bike.year %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/bikes/show.html.erb
<h2>Showing Bike</h2>

<dl class="attributes">
  <dt>Name</dt>
  <dl><%= @bike.name %></dl>
  <dt>Year</dt>
  <dl><%= @bike.year %></dl>
</dl>

<div class="actions">
<%= link_to 'Edit', edit_bike_path(@bike) %>

<%= link_to 'Delete', bike_path(@bike), method: :delete %>
</div>

app/views/bugs/edit.html.erb
<h2>Edit Bug</h2>

<%= form_for @bug do |f| %>

  <% if @bug.errors.present? %>
    <div class="errors">
      <h1>You fucked up!</h1>
      <ul class="erros-list">
        <% @bug.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :bug_name, "Bug Name" %>
    <%= f.text_field :bug_name, class: "form-label"%>
  </p>

  <p>
    <%= f.label :color, "Color" %>
    <%= f.text_field :color, class: "form-label" %>
  </p>

  <p>
    <%= f.submit "Update", class: "form-button"%>
  </p>
<% end %>

app/views/bugs/index.html.erb
<h2>Add a Bug</h2>

<%= form_for @bug do |f| %>

  <% if @bug.errors.present? %>
    <div class="errors">
      <h1>You fucked up!</h1>
      <ul class="erros-list">
        <% @bug.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :bug_name, "Bug Name", class: "form-label" %>
    <%= f.text_field :bug_name %>
  </p>

  <p>
    <%= f.label :color, "Color", class: "form-label" %>
    <%= f.text_field :color  %>
  </p>

  <p>
    <%= f.submit "Add Bug", class: "form-button" %>
  </p>
<% end %>

<table width="500" border="black">
  <caption><h2>Bugs</h2></caption>
  <thead>
  <th>Name</th>
  <th>Color</th>
  </thead>
  <% @bugs.each do |bug| %>
    <tbody>
    <tr>
      <td><%= link_to bug.bug_name, bug_path(bug) %></td>
      <td><%= bug.color %></td>
    </tr>
    </tbody>
  <% end %>
</table>

app/views/bugs/show.html.erb
<h2>Showing Bug</h2>

<dl class="attributes">
  <dt>Name</dt>
  <dl><%= @bug.bug_name %></dl>
  <dt>Color</dt>
  <dl><%= @bug.color %></dl>
</dl>

<div class="actions">
  <%= link_to 'Edit', edit_bug_path(@bug) %> |

  <%= link_to 'Delete', bug_path(@bug), method: :delete %>
</div>

app/views/cars/edit.html.erb
<h2>Update Car</h2>

<%= form_for @car do |f| %>

  <p>
    <%= f.label :model, "Name" %>
    <%= f.text_field :model, class: "form-label" %>
  </p>

  <p>
    <%= f.label :year, "Year" %>
    <%= f.text_field :year, class:"form-label" %>
  </p>

  <p>
    <%= f.submit "Update", class:"form-button" %>
  </p>
<% end %>

app/views/cars/index.html.erb
<h2>Add A Car</h2>
<%= form_for @car do |f| %>

  <p>
    <%= f.label :model, class: "form-label" %>
    <%= f.text_field :model %>
  </p>

  <p>
    <%= f.label :year, class: "form-label" %>
    <%= f.text_field :year %>
  </p>

  <p>
    <%= f.submit "Add Car", class: "form-button" %>
  </p>
<% end %>

<table width="500" border="black">
  <thead>
  <caption><h2>Cars</h2></caption>
  <th>Model</th>
  <th>Year</th>
  </thead>
  <tbody>
  <% @cars.each do |car| %><tr>
    <td><%= link_to car.model, car_path(car) %></td>
    <td><%= car.year %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/cars/show.html.erb
<h2>Showing Car</h2>

<dl class="attributes">
  <dt>Model</dt>
  <dl><%= @car.model %></dl>
  <dt>Year</dt>
  <dl><%= @car.year %></dl>
</dl>

<div class="actions">
  <%= link_to "Edit", edit_car_path(@car.id) %>

  <%= link_to "Delete", car_path(@car.id), method: :delete %>
</div>

app/views/fruits/edit.html.erb
<form action="/fruits/<%= @fruit.id %>" method="post">
  <input type="hidden" name="_method" value="put"/>
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>

  <p>
    <label for="fruit_name" class="form-label">Fruit Name</label>
    <input name="fruit[name]" id="fruit_name" value="<%= @fruit.name %>">
  </p>

  <p>
    <label for="fruit_description" class="form-label">Fruit Description</label>
    <input name="fruit[description]" id="fruit_description" value="<%= @fruit.description %>">
  </p>

  <p>
    <input type="submit" value="Update Fruit" class="form-button">
  </p>
  </form>

app/views/fruits/index.html.erb
<h1>Add A Fruit</h1>

<form action="/fruits" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

  <p>
    <label for="fruit_name" class="form-label">Fruit Name</label>
    <input name="fruit[name]" id="fruit_name">
  </p>

  <p>
    <label for="fruit_description" class="form-label">Fruit Description</label>
    <input name="fruit[description]" id="fruit_description">
  </p>

  <p>
    <input type="submit" value="Add Fruit" class="form-button">
  </p>
</form>

  <table width="500" border="black">
    <thead>
    <th>Name</th><th>Description</th>
    </thead>
    <% @fruits.each do |fruit| %>
  <tr><td><a href="/fruits/<%=fruit.id %>"><%= fruit.name %></a></td>
    <td><a href="/fruits/<%=fruit.id %>"><%= fruit.description %></a></td></tr>
  <% end %>
  </table>

app/views/fruits/show.html.erb
<div><h1>Fruits</h1>
</div><br><br>
<form action="/fruits/<%= @fruit.id %>" method="post" class="delete-form">
  <input type="hidden" name="_method" value="delete" />
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
  <input type="submit" value="Delete">
</form>
<table width="200">
  <tr>
    <td><strong><a href="/fruits/<%= @fruit.id %>/edit">Edit</a></strong></td>
  </tr>


  <tr>
    <td><p><strong>Fruit Name:</strong></td>
    <td><%= @fruit.name %></a></td>
    <br><br>
  </tr>
  <tr>
    <td><strong>Fruit Description:</strong></td>
    <td><%= @fruit.description %></a></p></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fruitastic</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="title-container">CRUD Practice
  </div>
</header>
<main>
<div class="show-container">
<%= yield %>
</div>
</main>
</body>
</html>

app/views/songs/edit.html.erb
<h2>Update Song</h2>

<%= form_for @song do |f| %>

  <p>
    <%= f.label :artist, class: "form-label" %>
    <%= f.text_field :artist %>
  </p>

  <p>
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>

<% end %>

app/views/songs/index.html.erb
<%= form_for @song do |f| %>
  <% if @song.errors.present? %>
    <div class="errors">
      <h1>Crap, that's not right!</h1>
      <ul class="erros-list">
        <% @song.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= f.label :artist, class: "form-label" %>
  <%= f.text_field :artist %>
</p>

<p>
  <%= f.label :title, class: "form-label" %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.submit "Add Song", class: "form-button" %>
</p>

<% end %>

<table width="500" border="black">
<caption><h2>Songs</h2></caption>
  <thead>
  <th>Artist</th>
  <th>Title</th>
  </thead>
  <tbody>
  <% @songs.each do |song| %>
  <tr>
    <td><%= link_to song.artist, song_path(song) %></td>
    <td><%= song.title %></td>
    <% end %>
  </tr>
  </tbody>
</table>

app/views/songs/show.html.erb
<h2>Showing Song</h2>

<dl class="attributes">
  <dt>Artist</dt>
  <dl><%= @song.artist%></dl>
  <dt>Title</dt>
  <dl><%= @song.title %></dl>
</dl>

<div class="actions">
  <%= link_to 'Edit', edit_song_path(@song) %> |
  <%= link_to 'Delete', song_path(@song), method: :delete %>
</div>

app/views/welcome/index.html.erb
<ul>
  <li>
    <a href="/fruits">Fruit</a>
  </li>
  <li>
    <a href="/bikes">Bikes</a>
  </li>
  <li>
    <%= link_to 'Bugs', bugs_path %>
  </li>

  <li>
    <%= link_to 'Songs', songs_path %>
  </li>

  <li>
    <%= link_to 'Cars', cars_path %>
  </li>
</ul>